
services:
  node_app:
    build:
      context: .  # Certifique-se de que o código da sua aplicação Node.js está neste diretório
    ports:
      - "3000:3000"
    depends_on:
      - mariadb_db
      - rabbitmq
    environment:
      - DB_HOST=mariadb_db
      - DB_USER=username
      - DB_PASSWORD=password
      - DB_NAME=library_db
      - RABBITMQ_URI=amqp://admin:admin@rabbitmq

  mariadb_db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: library_db
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: admin 
      RABBITMQ_DEFAULT_PASS: admin 
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq

volumes:
  rabbitmq-data:
  rabbitmq-log:
